services:

  django:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8000:8000"

    environment:
      DJANGO_SETTINGS_MODULE: "pidproject.docker_settings"

      DJANGO_SECRET_KEY: "${DJANGO_SECRET_KEY}"

      DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1"

      DJANGO_CSRF_TRUSTED_ORIGINS: "http://localhost:8000"

      DJANGO_DB_ENGINE: "django.db.backends.sqlite3"
      DJANGO_DB_NAME: "/data/db.sqlite3"

      GO_BACKEND_URL: "http://backend:8080"
      GO_BACKEND_TOKEN: "${GO_BACKEND_TOKEN}"

      KEYCLOAK_CLIENT_ID: "${KEYCLOAK_CLIENT_ID}"
      KEYCLOAK_CLIENT_SECRET: "${KEYCLOAK_CLIENT_SECRET}"
      KEYCLOAK_SERVER_METADATA_URL: "${KEYCLOAK_SERVER_METADATA_URL}"
      KEYCLOAK_ALLOWED_GROUP: "${KEYCLOAK_ALLOWED_GROUP}"
      FRONTEND_URL: "http://localhost:8000/frontend"

    depends_on:
      - backend

    volumes:
      - django-data:/data


  backend:
    build:
      context: ../quickpid
      dockerfile: Dockerfile.sqlite

    volumes:
      - quickpid-sqlite:/data


volumes:
  django-data:
  quickpid-sqlite:
