[uwsgi]

# network settings
http-socket = :8000

# django settings
chdir = /app
module = pidproject.wsgi
buffer-size = 16384

# exceptions please
log-5xx = true
py-capture-error-output = true
catch-stderr = true

# static files
mime-file = /etc/mime.types
static-map = /static=/var/www/static
static-index = index.html
static-map = /frontend/=/var/www/frontend/
# process settings
master = 1
vacuum = True
processes = 2
threads = 2
max-requests = 5000
