# Generated by Django 6.0.5 on 2026-06-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pidmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namespacepermission',
            name='permission',
            field=models.CharField(choices=[('read', 'Read'), ('create', 'Create'), ('update', 'Update/Delete'), ('mount', 'Mount'), ('list', 'List')], max_length=20),
        ),
    ]
